
import Head from 'next/head'
import Footer from './components/footer'
import Nav from './components/nav'
import Homepage from './homepage'
export default function Home() {
  return (

    <div >
      <Head>
        <title>magoso school</title>
        <meta name="description" content="Generated by create next app" />
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>

      
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous"></link>
      </Head>
      <body>

      <Nav/>
  <Homepage/>
  <Footer/>
      </body>

  
    </div>



import ContactInfo from "./contact/contactInfo";
import Contact from "./contact/contact"
export default function Home() {
  return (
    <div>
<Contact/>
<ContactInfo/>
    </div>
    

  )
}
