
import Head from 'next/head'
import React from 'react'

// import Image from 'next/image'
import Donation from './api/components/Donation'
import Founders from './components/Founders'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Donation/>
        <Founders/>

      </div>


</div>
)
  }

